### PR TITLE
toh

### PR DESCRIPTION
**Pull request by Anaa29**
FOR HACKTOBERFEST 2021

### CODE REVIEW

**Comment by Riddhesh06** [comment]
whats this ??

**Comment by Anaa29** [comment]
Tower of Hanoi solved using recursion algo

**Comment by Anaa29** [comment]
In Tower of Hanoi problem, we need to transfer given no of disc's i.e. n from source to destination using mediator tower...with conditions
Disc's in source are arranged in decreasing order i.e. 1st disc is of diameter 1 and last of n, we can only move one disc at a time and can't keep larger disc on smaller disc.
Recursion func basically returns instructions to transfer disc's from source to destination using mediator tower.

**Comment by Riddhesh06** [comment]
ok ! all the best

**Comment by Anaa29** [comment]
Thanks ;)

**Pull request merged**
